skip_frontmatter: true

linters:
  CommentControlStatement:
    enabled: true

  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 2

  EmptyControlStatement:
    enabled: true

  LineLength:
    enabled: true
    max: 80

  RedundantDiv:
    enabled: false

  RuboCop:
    enabled: false

  TagCase:
    enabled: true

  TrailingWhitespace:
    enabled: true
